const FLUFFOS_PREDEFINED_MACROS = new Set([
    'FLUFFOS',
    'HAS_DEBUG_LEVEL',
    'HAS_ED',
    'HAS_PRINTF',
    'HAS_RUSAGE',
    'MAX_FLOAT',
    'MAX_INT',
    'MIN_FLOAT',
    'MIN_INT',
    'MUDOS',
    'MUD_NAME',
    'SIZEOFINT',
    '__ARCH__',
    '__ARGUMENTS_IN_TRACEBACK__',
    '__ARRAY_STATS__',
    '__AUTO_SETEUID__',
    '__CACHE_STATS__',
    '__CALLOUT_HANDLES__',
    '__CALL_OTHER_TYPE_CHECK__',
    '__CALL_OTHER_WARN__',
    '__CFG_COMPILER_STACK_SIZE__',
    '__CFG_EVALUATOR_STACK_SIZE__',
    '__CFG_MAX_CALL_DEPTH__',
    '__CFG_MAX_GLOBAL_VARIABLES__',
    '__CLASS_STATS__',
    '__COMMAND_BUF_SIZE__',
    '__COMPILER__',
    '__CXXFLAGS__',
    '__DEBUG_MACRO__',
    '__DEBUG__',
    '__DEFAULT_DB__',
    '__DEFAULT_PRAGMAS__',
    '__DIR__',
    '__DSLIB__',
    '__DWLIB__',
    '__ED_INDENT_SPACES__',
    '__ED_TAB_WIDTH__',
    '__FILE__',
    '__GET_CHAR_IS_BUFFERED__',
    '__HAS_CONSOLE__',
    '__HAVE_DIRENT_H__',
    '__HAVE_JEMALLOC__',
    '__HAVE_SIGNAL_H__',
    '__HAVE_SYS_STAT_H__',
    '__HAVE_SYS_TIME_H__',
    '__HAVE_TIME_H__',
    '__INTERACTIVE_CATCH_TELL__',
    '__LARGEST_PRINTABLE_STRING__',
    '__LARGE_STRING_SIZE__',
    '__LAZY_RESETS__',
    '__LINE__',
    '__LOCALS_IN_TRACEBACK__',
    '__MAX_SAVE_SVALUE_DEPTH__',
    '__MUDLIB_ERROR_HANDLER__',
    '__NONINTERACTIVE_STDERR_WRITE__',
    '__NO_RESETS__',
    '__OLD_ED__',
    '__OLD_RANGE_BEHAVIOR__',
    '__OLD_TYPE_BEHAVIOR__',
    '__PACKAGES_PACKAGES_H__',
    '__PACKAGE_ASYNC__',
    '__PACKAGE_COMPRESS__',
    '__PACKAGE_CONTRIB__',
    '__PACKAGE_CORE__',
    '__PACKAGE_DB__',
    '__PACKAGE_DEVELOP__',
    '__PACKAGE_EXTERNAL__',
    '__PACKAGE_JSON__',
    '__PACKAGE_MATH__',
    '__PACKAGE_MATRIX__',
    '__PACKAGE_MUDLIB_STATS__',
    '__PACKAGE_OPS__',
    '__PACKAGE_PARSER__',
    '__PACKAGE_PCRE__',
    '__PACKAGE_SHA1__',
    '__PACKAGE_SOCKETS__',
    '__PACKAGE_TRIM__',
    '__PACKAGE_UIDS__',
    '__PARSE_DEBUG__',
    '__PORT__',
    '__PRIVS__',
    '__PROJECT_VERSION__',
    '__RANDOMIZED_RESETS__',
    '__RECEIVE_SNOOP__',
    '__REF_RESERVED_WORD__',
    '__RESTRICTED_ED__',
    '__REVERSE_DEFER__',
    '__REVERSIBLE_EXPLODE_STRING__',
    '__SANE_EXPLODE_STRING__',
    '__SANE_SORTING__',
    '__SAVE_EXTENSION__',
    '__SAVE_GZ_EXTENSION__',
    '__SENSIBLE_MODIFIERS__',
    '__SMALL_STRING_SIZE__',
    '__SNOOP_SHADOWED__',
    '__STRING_STATS__',
    '__STRUCT_CLASS__',
    '__STRUCT_STRUCT__',
    '__SUPPRESS_ARGUMENT_WARNINGS__',
    '__THIS_PLAYER_IN_CALL_OUT__',
    '__TIME_WITH_SYS_TIME__',
    '__TRACE_CODE__',
    '__TRACE__',
    '__TRAP_CRASHES__',
    '__USE_32BIT_ADDRESSES__',
    '__USE_MYSQL__',
    '__USE_POSTGRES__',
    '__USE_SQLITE3__',
    '__VERSION__',
    '__WARN_OLD_RANGE_BEHAVIOR__',
    '__WOMBLES__'
]);

const FLUFFOS_GENERATED_PREDEFINE_PATTERNS = [
    /^__CFG_[A-Z0-9_]+__$/,
    /^__HAVE_[A-Z0-9_]+__$/,
    /^__PACKAGE_[A-Z0-9_]+__$/
];

const FLUFFOS_PREDEFINED_MACRO_VALUE_TYPES = new Map<string, string>([
    ['__DIR__', 'string'],
    ['__FILE__', 'string'],
    ['__LINE__', 'int']
]);

export function isFluffOSPredefinedMacro(name: string): boolean {
    return FLUFFOS_PREDEFINED_MACROS.has(name)
        || FLUFFOS_GENERATED_PREDEFINE_PATTERNS.some((pattern) => pattern.test(name));
}

export function getFluffOSPredefinedMacroValueType(name: string): string | undefined {
    return FLUFFOS_PREDEFINED_MACRO_VALUE_TYPES.get(name);
}
